<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert(array(
            array('name' => 'Afganisztán', 'flag' => 'AF.png', 'iso_alpha3' => 'AFG'),
            array('name' => 'Albánia', 'flag' => 'AL.png', 'iso_alpha3' => 'ALB'),
            array('name' => 'Algéria', 'flag' => 'DZ.png', 'iso_alpha3' => 'DZA'),
            array('name' => 'Amerikai Szamoa', 'flag' => 'AS.png', 'iso_alpha3' => 'ASM'),
            array('name' => 'Amerikai Virgin-szigetek', 'flag' => 'VI.png', 'iso_alpha3' => 'VIR'),
            array('name' => 'Andorra', 'flag' => 'AND.png', 'iso_alpha3' => 'AND'),
            array('name' => 'Angola', 'flag' => 'AO.png', 'iso_alpha3' => 'AOA'),
            array('name' => 'Anguilla', 'flag' => 'AI.png', 'iso_alpha3' => 'AIA'),
            array('name' => 'Antarktisz', 'flag' => 'AQ.png', 'iso_alpha3' => 'ATA'),
            array('name' => 'Antigua és Barbuda', 'flag' => 'AG.png', 'iso_alpha3' => 'ATG'),
            array('name' => 'Argentína', 'flag' => 'AR.png', 'iso_alpha3' => 'ARG'),
            array('name' => 'Aruba', 'flag' => 'AW.png', 'iso_alpha3' => 'AWG'),
            array('name' => 'Ausztria', 'flag' => 'AT.png', 'iso_alpha3' => 'AUT'),
            array('name' => 'Ausztrália', 'flag' => 'AU.png', 'iso_alpha3' => 'AUS'),
            array('name' => 'Azerbajdzsán', 'flag' => 'AZ.png', 'iso_alpha3' => 'AZE'),
            array('name' => 'Bahamák', 'flag' => 'BS.png', 'iso_alpha3' => 'BHS'),
            array('name' => 'Bahrein', 'flag' => 'BH.png', 'iso_alpha3' => 'BHR'),
            array('name' => 'Banglades', 'flag' => 'BD.png', 'iso_alpha3' => 'BGD'),
            array('name' => 'Barbados', 'flag' => 'BB.png', 'iso_alpha3' => 'BRB'),
            array('name' => 'Belgium', 'flag' => 'BE.png', 'iso_alpha3' => 'BEL'),
            array('name' => 'Belize', 'flag' => 'BZ.png', 'iso_alpha3' => 'BLZ'),
            array('name' => 'Benin', 'flag' => 'BJ.png', 'iso_alpha3' => 'BEN'),
            array('name' => 'Bermuda', 'flag' => 'BM.png', 'iso_alpha3' => 'BMU'),
            array('name' => 'Bhután', 'flag' => 'BT.png', 'iso_alpha3' => 'BTN'),
            array('name' => 'Bolívia', 'flag' => 'BO.png', 'iso_alpha3' => 'BOL'),
            array('name' => 'Bosznia-Hercegovina', 'flag' => 'BA.png', 'iso_alpha3' => 'BIH'),
            array('name' => 'Botswana', 'flag' => 'BW.png', 'iso_alpha3' => 'BWA'),
            array('name' => 'Bouvet-sziget', 'flag' => 'BV.png', 'iso_alpha3' => 'BVT'),
            array('name' => 'Brazília', 'flag' => 'BR.png', 'iso_alpha3' => 'BRA'),
            array('name' => 'Brit Indiai Oceán', 'flag' => 'IO.png', 'iso_alpha3' => 'IOT'),
            array('name' => 'Brit Virgin-szigetek', 'flag' => 'VG.png', 'iso_alpha3' => 'VGB'),
            array('name' => 'Brunei', 'flag' => 'BN.png', 'iso_alpha3' => 'BRN'),
            array('name' => 'Bulgária', 'flag' => 'BG.png', 'iso_alpha3' => 'BGR'),
            array('name' => 'Burkina Faso', 'flag' => 'BF.png', 'iso_alpha3' => 'BFA'),
            array('name' => 'Burundi', 'flag' => 'BI.png', 'iso_alpha3' => 'BDI'),
            array('name' => 'Chile', 'flag' => 'CL.png', 'iso_alpha3' => 'CHL'),
            array('name' => 'Ciprus', 'flag' => 'CY.png', 'iso_alpha3' => 'CYP'),
            array('name' => 'Comore-szigetek', 'flag' => 'KM.png', 'iso_alpha3' => 'COM'),
            array('name' => 'Cook-szigetek', 'flag' => 'CK.png', 'iso_alpha3' => 'COK'),
            array('name' => 'Costa Rica', 'flag' => 'CR.png', 'iso_alpha3' => 'CRI'),
            array('name' => 'Csehország', 'flag' => 'CZ.png', 'iso_alpha3' => 'CZE'),
            array('name' => 'Csád', 'flag' => 'TD.png', 'iso_alpha3' => 'TCD'),
            array('name' => 'Dominika', 'flag' => 'DM.png', 'iso_alpha3' => 'DMA'),
            array('name' => 'Dominikai Köztársaság', 'flag' => 'DO.png', 'iso_alpha3' => 'DOM'),
            array('name' => 'Dzsibuti', 'flag' => 'DJ.png', 'iso_alpha3' => 'DJI'),
            array('name' => 'Dánia', 'flag' => 'DK.png', 'iso_alpha3' => 'DNK'),
            array('name' => 'Dél Grúzia és a Déli Szendvics-szigetek', 'flag' => 'GS.png', 'iso_alpha3' => 'SGS'),
            array('name' => 'Dél-Afrika', 'flag' => 'ZA.png', 'iso_alpha3' => 'ZAF'),
            array('name' => 'Dél-Korea', 'flag' => 'KR.png', 'iso_alpha3' => 'KOR'),
            array('name' => 'Ecuador', 'flag' => 'EC.png', 'iso_alpha3' => 'ECU'),
            array('name' => 'Egyenlítői-Guinea', 'flag' => 'GQ.png', 'iso_alpha3' => 'GNQ'),
            array('name' => 'Egyesült Arab Emirátus', 'flag' => 'AE.png', 'iso_alpha3' => 'ARE'),
            array('name' => 'Egyesült Királyság', 'flag' => 'GB.png', 'iso_alpha3' => 'GBR'),
            array('name' => 'Egyesült Államok', 'flag' => 'US.png', 'iso_alpha3' => 'USA'),
            array('name' => 'Egyiptom', 'flag' => 'EG.png', 'iso_alpha3' => 'EGY'),
            array('name' => 'Elefántcsontpart', 'flag' => 'CI.png', 'iso_alpha3' => 'CIV'),
            array('name' => 'Eritrea', 'flag' => 'ER.png', 'iso_alpha3' => 'ERI'),
            array('name' => 'Etiópia', 'flag' => 'ET.png', 'iso_alpha3' => 'ETH'),
            array('name' => 'Észak-Korea', 'flag' => 'KP.png', 'iso_alpha3' => 'PRK'),
            array('name' => 'Északi Mariana-szigetek', 'flag' => 'MP.png', 'iso_alpha3' => 'MNP'),
            array('name' => 'Észtország', 'flag' => 'EE.png', 'iso_alpha3' => 'EST'),
            array('name' => 'Falkland-szigetek', 'flag' => 'FK.png', 'iso_alpha3' => 'FLK'),
            array('name' => 'Fehéroroszország', 'flag' => 'BY.png', 'iso_alpha3' => 'BLR'),
            array('name' => 'Feröer-szigetek', 'flag' => 'FO.png', 'iso_alpha3' => 'FRO'),
            array('name' => 'Fidzsi', 'flag' => 'FJ.png', 'iso_alpha3' => 'FJI'),
            array('name' => 'Finnország', 'flag' => 'FI.png', 'iso_alpha3' => 'FIN'),
            array('name' => 'Francia Déli Területek', 'flag' => 'TF.png', 'iso_alpha3' => 'ATF'),
            array('name' => 'Francia Guyana', 'flag' => 'GF.png', 'iso_alpha3' => 'GUF'),
            array('name' => 'Francia Polinézia', 'flag' => 'PF.png', 'iso_alpha3' => 'PYF'),
            array('name' => 'Franciaország', 'flag' => 'FR.png', 'iso_alpha3' => 'FRA'),
            array('name' => 'Fülöp-szigetek', 'flag' => 'PH.png', 'iso_alpha3' => 'PHL'),
            array('name' => 'Gabon', 'flag' => 'GA.png', 'iso_alpha3' => 'GAB'),
            array('name' => 'Gambia', 'flag' => 'GM.png', 'iso_alpha3' => 'GMB'),
            array('name' => 'Ghána', 'flag' => 'GH.png', 'iso_alpha3' => 'GHA'),
            array('name' => 'Gibraltár', 'flag' => 'GI.png', 'iso_alpha3' => 'GIB'),
            array('name' => 'Grenada', 'flag' => 'GD.png', 'iso_alpha3' => 'GRD'),
            array('name' => 'Grönland', 'flag' => 'GL.png', 'iso_alpha3' => 'GRL'),
            array('name' => 'Grúzia', 'flag' => 'GE.png', 'iso_alpha3' => 'GEO'),
            array('name' => 'Guadeloupe', 'flag' => 'GP.png', 'iso_alpha3' => 'GLP'),
            array('name' => 'Guam', 'flag' => 'GU.png', 'iso_alpha3' => 'GUM'),
            array('name' => 'Guatemala', 'flag' => 'GT.png', 'iso_alpha3' => 'GTM'),
            array('name' => 'Guinea', 'flag' => 'GN.png', 'iso_alpha3' => 'GIN'),
            array('name' => 'Guinea-Bissau', 'flag' => 'GW.png', 'iso_alpha3' => 'GNB'),
            array('name' => 'Guyana', 'flag' => 'GY.png', 'iso_alpha3' => 'GUY'),
            array('name' => 'Görögország', 'flag' => 'GR.png', 'iso_alpha3' => 'GRC'),
            array('name' => 'Haiti', 'flag' => 'HT.png', 'iso_alpha3' => 'HTI'),
            array('name' => 'Heard és McDonald Szigetek', 'flag' => 'HM.png', 'iso_alpha3' => 'HMD'),
            array('name' => 'Holland Antillák', 'flag' => 'AN.png', 'iso_alpha3' => 'ANT'),
            array('name' => 'Hollandia', 'flag' => 'NL.png', 'iso_alpha3' => 'NLD'),
            array('name' => 'Honduras', 'flag' => 'HN.png', 'iso_alpha3' => 'HND'),
            array('name' => 'Hongkong', 'flag' => 'HK.png', 'iso_alpha3' => 'HKG'),
            array('name' => 'Horvátország', 'flag' => 'HR.png', 'iso_alpha3' => 'HRV'),
            array('name' => 'India', 'flag' => 'IN.png', 'iso_alpha3' => 'IND'),
            array('name' => 'Indonézia', 'flag' => 'ID.png', 'iso_alpha3' => 'IDN'),
            array('name' => 'Irak', 'flag' => 'IQ.png', 'iso_alpha3' => 'IRQ'),
            array('name' => 'Irán', 'flag' => 'IR.png', 'iso_alpha3' => 'IRN'),
            array('name' => 'Izland', 'flag' => 'IS.png', 'iso_alpha3' => 'ISL'),
            array('name' => 'Izrael', 'flag' => 'IL.png', 'iso_alpha3' => 'ISR'),
            array('name' => 'Írország', 'flag' => 'IE.png', 'iso_alpha3' => 'IRL'),
            array('name' => 'Jamaica', 'flag' => 'JM.png', 'iso_alpha3' => 'JAM'),
            array('name' => 'Japán', 'flag' => 'JP.png', 'iso_alpha3' => 'JPN'),
            array('name' => 'Jemen', 'flag' => 'YE.png', 'iso_alpha3' => 'YEM'),
            array('name' => 'Jordánia', 'flag' => 'JO.png', 'iso_alpha3' => 'JOR'),
            array('name' => 'Kajmán-szigetek', 'flag' => 'KY.png', 'iso_alpha3' => 'CYM'),
            array('name' => 'Kambodzsa', 'flag' => 'KH.png', 'iso_alpha3' => 'KHM'),
            array('name' => 'Kamerun', 'flag' => 'CM.png', 'iso_alpha3' => 'CMR'),
            array('name' => 'Kanada', 'flag' => 'CA.png', 'iso_alpha3' => 'CAN'),
            array('name' => 'Karácsony-szigetek', 'flag' => 'CX.png', 'iso_alpha3' => 'CXR'),
            array('name' => 'Katar', 'flag' => 'QA.png', 'iso_alpha3' => 'QAT'),
            array('name' => 'Kazahsztán', 'flag' => 'KZ.png', 'iso_alpha3' => 'KAZ'),
            array('name' => 'Kelet-Timor', 'flag' => 'TL.png', 'iso_alpha3' => 'TLS'),
            array('name' => 'Kenya', 'flag' => 'KE.png', 'iso_alpha3' => 'KEN'),
            array('name' => 'Kirgizisztán', 'flag' => 'KG.png', 'iso_alpha3' => 'KGZ'),
            array('name' => 'Kiribati', 'flag' => 'KI.png', 'iso_alpha3' => 'KIR'),
            array('name' => 'Kolumbia', 'flag' => 'CO.png', 'iso_alpha3' => 'COL'),
            array('name' => 'Kongó', 'flag' => 'CG.png', 'iso_alpha3' => 'COG'),
            array('name' => 'Kongói Demokratikus Köztársaság', 'flag' => 'CD.png', 'iso_alpha3' => 'COD'),
            array('name' => 'Kuba', 'flag' => 'CU.png', 'iso_alpha3' => 'CUB'),
            array('name' => 'Kuvait', 'flag' => 'KW.png', 'iso_alpha3' => 'KWT'),
            array('name' => 'Kína', 'flag' => 'CN.png', 'iso_alpha3' => 'CHN'),
            array('name' => 'Kókusz-szigetek', 'flag' => 'CC.png', 'iso_alpha3' => 'CCK'),
            array('name' => 'Közép-afrikai Köztársaság', 'flag' => 'CF.png', 'iso_alpha3' => 'CAF'),
            array('name' => 'Laosz', 'flag' => 'LA.png', 'iso_alpha3' => 'LAO'),
            array('name' => 'Lengyelország', 'flag' => 'PL.png', 'iso_alpha3' => 'POL'),
            array('name' => 'Lesotho', 'flag' => 'LS.png', 'iso_alpha3' => 'LSO'),
            array('name' => 'Lettország', 'flag' => 'LV.png', 'iso_alpha3' => 'LVA'),
            array('name' => 'Libanon', 'flag' => 'LB.png', 'iso_alpha3' => 'LBN'),
            array('name' => 'Libéria', 'flag' => 'LR.png', 'iso_alpha3' => 'LBR'),
            array('name' => 'Liechtenstein', 'flag' => 'LI.png', 'iso_alpha3' => 'LIE'),
            array('name' => 'Litvánia', 'flag' => 'LT.png', 'iso_alpha3' => 'LTU'),
            array('name' => 'Luxemburg', 'flag' => 'LU.png', 'iso_alpha3' => 'LUX'),
            array('name' => 'Líbia', 'flag' => 'LY.png', 'iso_alpha3' => 'LBY'),
            array('name' => 'Macedónia', 'flag' => 'MK.png', 'iso_alpha3' => 'MKD'),
            array('name' => 'Madagaszkár', 'flag' => 'MG.png', 'iso_alpha3' => 'MDG'),
            array('name' => 'Magyarország', 'flag' => 'HU.png', 'iso_alpha3' => 'HUN'),
            array('name' => 'Makaó', 'flag' => 'MO.png', 'iso_alpha3' => 'MAC'),
            array('name' => 'Malajzia', 'flag' => 'MY.png', 'iso_alpha3' => 'MYS'),
            array('name' => 'Malawi', 'flag' => 'MW.png', 'iso_alpha3' => 'MWI'),
            array('name' => 'Maldív-szigetek', 'flag' => 'MV.png', 'iso_alpha3' => 'MDV'),
            array('name' => 'Mali', 'flag' => 'ML.png', 'iso_alpha3' => 'MLI'),
            array('name' => 'Marokkó', 'flag' => 'MA.png', 'iso_alpha3' => 'MAR'),
            array('name' => 'Marshall-szigetek', 'flag' => 'MH.png', 'iso_alpha3' => 'MHL'),
            array('name' => 'Martinique', 'flag' => 'MQ.png', 'iso_alpha3' => 'MTQ'),
            array('name' => 'Mauritius', 'flag' => 'MU.png', 'iso_alpha3' => 'MUS'),
            array('name' => 'Mauritánia', 'flag' => 'MR.png', 'iso_alpha3' => 'MRT'),
            array('name' => 'Mayotte', 'flag' => 'YT.png', 'iso_alpha3' => 'MYT'),
            array('name' => 'Mexikó', 'flag' => 'MX.png', 'iso_alpha3' => 'MEX'),
            array('name' => 'Mianmar', 'flag' => 'MM.png', 'iso_alpha3' => 'MMR'),
            array('name' => 'Mikronézia', 'flag' => 'FM.png', 'iso_alpha3' => 'FSM'),
            array('name' => 'Moldova', 'flag' => 'MD.png', 'iso_alpha3' => 'MDA'),
            array('name' => 'Monaco', 'flag' => 'MC.png', 'iso_alpha3' => 'MCO'),
            array('name' => 'Mongólia', 'flag' => 'MN.png', 'iso_alpha3' => 'MNG'),
            array('name' => 'Montenegró', 'flag' => 'ME.png', 'iso_alpha3' => 'MNE'),
            array('name' => 'Montserrat', 'flag' => 'MS.png', 'iso_alpha3' => 'MSR'),
            array('name' => 'Mozambik', 'flag' => 'MZ.png', 'iso_alpha3' => 'MOZ'),
            array('name' => 'Málta', 'flag' => 'ML.png', 'iso_alpha3' => 'MLT'),
            array('name' => 'Namíbia', 'flag' => 'NA.png', 'iso_alpha3' => 'NAM'),
            array('name' => 'Nauru', 'flag' => 'NR.png', 'iso_alpha3' => 'NRU'),
            array('name' => 'Nepál', 'flag' => 'NP.png', 'iso_alpha3' => 'NPL'),
            array('name' => 'Nicaragua', 'flag' => 'NI.png', 'iso_alpha3' => 'NIC'),
            array('name' => 'Niger', 'flag' => 'NE.png', 'iso_alpha3' => 'NER'),
            array('name' => 'Nigéria', 'flag' => 'NG.png', 'iso_alpha3' => 'NGA'),
            array('name' => 'Niue', 'flag' => 'NU.png', 'iso_alpha3' => 'NIU'),
            array('name' => 'Norfolk-sziget', 'flag' => 'NF.png', 'iso_alpha3' => 'NFK'),
            array('name' => 'Norvégia', 'flag' => 'NO.png', 'iso_alpha3' => 'NOR'),
            array('name' => 'Nyugat-Szahara', 'flag' => 'EH.png', 'iso_alpha3' => 'ESH'),
            array('name' => 'Németország', 'flag' => 'DE.png', 'iso_alpha3' => 'DEU'),
            array('name' => 'Olaszország', 'flag' => 'IT.png', 'iso_alpha3' => 'ITA'),
            array('name' => 'Omán', 'flag' => 'OM.png', 'iso_alpha3' => 'OMN'),
            array('name' => 'Oroszország', 'flag' => 'RU.png', 'iso_alpha3' => 'RUS'),
            array('name' => 'Örményország', 'flag' => 'AM.png', 'iso_alpha3' => 'ARM'),
            array('name' => 'Pakisztán', 'flag' => 'PK.png', 'iso_alpha3' => 'PAK'),
            array('name' => 'Palau', 'flag' => 'PW.png', 'iso_alpha3' => 'PLW'),
            array('name' => 'Palesztin Terület', 'flag' => 'PS.png', 'iso_alpha3' => 'PSE'),
            array('name' => 'Panama', 'flag' => 'PA.png', 'iso_alpha3' => 'PAN'),
            array('name' => 'Paraguay', 'flag' => 'PY.png', 'iso_alpha3' => 'PRY'),
            array('name' => 'Peru', 'flag' => 'PE.png', 'iso_alpha3' => 'PER'),
            array('name' => 'Pitcairn-sziget', 'flag' => 'PN.png', 'iso_alpha3' => 'PCN'),
            array('name' => 'Portugália', 'flag' => 'PT.png', 'iso_alpha3' => 'PRT'),
            array('name' => 'Puerto Rico', 'flag' => 'PR.png', 'iso_alpha3' => 'PRI'),
            array('name' => 'Pápua Új-Guinea', 'flag' => 'PG.png', 'iso_alpha3' => 'PNG'),
            array('name' => 'Reunion', 'flag' => 'RE.png', 'iso_alpha3' => 'REU'),
            array('name' => 'Románia', 'flag' => 'RO.png', 'iso_alpha3' => 'ROU'),
            array('name' => 'Ruanda', 'flag' => 'RW.png', 'iso_alpha3' => 'RWA'),
            array('name' => 'Saint Kitts és Nevis', 'flag' => 'KN.png', 'iso_alpha3' => 'KNA'),
            array('name' => 'Saint Pierre és Miquelon', 'flag' => 'PM.png', 'iso_alpha3' => 'SPM'),
            array('name' => 'Saint Vincent és Grenadines', 'flag' => 'VC.png', 'iso_alpha3' => 'VCT'),
            array('name' => 'Salamon-szigetek', 'flag' => 'SB.png', 'iso_alpha3' => 'SLB'),
            array('name' => 'Salvador', 'flag' => 'SV.png', 'iso_alpha3' => 'SLV'),
            array('name' => 'San Marino', 'flag' => 'SM.png', 'iso_alpha3' => 'SMR'),
            array('name' => 'Santa Lucia', 'flag' => 'LC.png', 'iso_alpha3' => 'LCA'),
            array('name' => 'Sao Tomé és Príncipe', 'flag' => 'ST.png', 'iso_alpha3' => 'STP'),
            array('name' => 'Seychelle-szigetek', 'flag' => 'SC.png', 'iso_alpha3' => 'SYC'),
            array('name' => 'Sierra Leone', 'flag' => 'SL.png', 'iso_alpha3' => 'SLE'),
            array('name' => 'Spanyolország', 'flag' => 'ES.png', 'iso_alpha3' => 'ESP'),
            array('name' => 'Srí Lanka', 'flag' => 'LK.png', 'iso_alpha3' => 'LKA'),
            array('name' => 'Suriname', 'flag' => 'SR.png', 'iso_alpha3' => 'SUR'),
            array('name' => 'Svalbard és Jan Mayen', 'flag' => 'SJ.png', 'iso_alpha3' => 'SJM'),
            array('name' => 'Svájc', 'flag' => 'CH.png', 'iso_alpha3' => 'CHE'),
            array('name' => 'Svédország', 'flag' => 'SE.png', 'iso_alpha3' => 'SWE'),
            array('name' => 'Szamoa', 'flag' => 'WS.png', 'iso_alpha3' => 'WSM'),
            array('name' => 'Szaúd-Arábia', 'flag' => 'SA.png', 'iso_alpha3' => 'SAU'),
            array('name' => 'Szenegál', 'flag' => 'SN.png', 'iso_alpha3' => 'SEN'),
            array('name' => 'Szent Helena', 'flag' => 'SH.png', 'iso_alpha3' => 'SHN'),
            array('name' => 'Szerbia', 'flag' => 'RS.png', 'iso_alpha3' => 'SRB'),
            array('name' => 'Szingapúr', 'flag' => 'SG.png', 'iso_alpha3' => 'SGP'),
            array('name' => 'Szlovákia', 'flag' => 'SK.png', 'iso_alpha3' => 'SVK'),
            array('name' => 'Szlovénia', 'flag' => 'SI.png', 'iso_alpha3' => 'SVN'),
            array('name' => 'Szomália', 'flag' => 'SO.png', 'iso_alpha3' => 'SOM'),
            array('name' => 'Szudán', 'flag' => 'SD.png', 'iso_alpha3' => 'SDN'),
            array('name' => 'Szváziföld', 'flag' => 'SZ.png', 'iso_alpha3' => 'SWZ'),
            array('name' => 'Szíria', 'flag' => 'SY.png', 'iso_alpha3' => 'SYR'),
            array('name' => 'Tadzsikisztán', 'flag' => 'TJ.png', 'iso_alpha3' => 'TJK'),
            array('name' => 'Tajvan', 'flag' => 'TW.png', 'iso_alpha3' => 'TWN'),
            array('name' => 'Tanzánia', 'flag' => 'TZ.png', 'iso_alpha3' => 'TZA'),
            array('name' => 'Thaiföld', 'flag' => 'TH.png', 'iso_alpha3' => 'THA'),
            array('name' => 'Togo', 'flag' => 'TG.png', 'iso_alpha3' => 'TGO'),
            array('name' => 'Tokelau', 'flag' => 'TK.png', 'iso_alpha3' => 'TKL'),
            array('name' => 'Tonga', 'flag' => 'TO.png', 'iso_alpha3' => 'TON'),
            array('name' => 'Trinidad és Tobago', 'flag' => 'TT.png', 'iso_alpha3' => 'TTO'),
            array('name' => 'Tunézia', 'flag' => 'TN.png', 'iso_alpha3' => 'TUN'),
            array('name' => 'Turks- és Caicos-szigetek', 'flag' => 'TC.png', 'iso_alpha3' => 'TCA'),
            array('name' => 'Tuvalu', 'flag' => 'TV.png', 'iso_alpha3' => 'TUV'),
            array('name' => 'Törökország', 'flag' => 'TR.png', 'iso_alpha3' => 'TUR'),
            array('name' => 'Türkmenisztán', 'flag' => 'TM.png', 'iso_alpha3' => 'TKM'),
            array('name' => 'Uganda', 'flag' => 'UG.png', 'iso_alpha3' => 'UGA'),
            array('name' => 'Ukrajna', 'flag' => 'UA.png', 'iso_alpha3' => 'UKR'),
            array('name' => 'Uruguay', 'flag' => 'UY.png', 'iso_alpha3' => 'URY'),
            array('name' => 'Új-Kaledónia', 'flag' => 'NC.png', 'iso_alpha3' => 'NCL'),
            array('name' => 'Új-Zéland', 'flag' => 'NZ.png', 'iso_alpha3' => 'NZL'),
            array('name' => 'Üzbegisztán', 'flag' => 'UZ.png', 'iso_alpha3' => 'UZB'),
            array('name' => 'Vanuatu', 'flag' => 'VU.png', 'iso_alpha3' => 'VUT'),
            array('name' => 'Vatikán', 'flag' => 'VA.png', 'iso_alpha3' => 'VAT'),
            array('name' => 'Venezuela', 'flag' => 'VE.png', 'iso_alpha3' => 'VEN'),
            array('name' => 'Vietnam', 'flag' => 'VN.png', 'iso_alpha3' => 'VNM'),
            array('name' => 'Wallis és Futuna', 'flag' => 'WF.png', 'iso_alpha3' => 'WLF'),
            array('name' => 'Zambia', 'flag' => 'ZM.png', 'iso_alpha3' => 'ZMB'),
            array('name' => 'Zimbabwe', 'flag' => 'ZW.png', 'iso_alpha3' => 'ZWE')
        ));
    }
}
